export default {
  UFS: [
    { value: "AC", text: "AC" },
    { value: "AL", text: "AL" },
    { value: "AM", text: "AM" },
    { value: "AP", text: "AP" },
    { value: "BA", text: "BA" },
    { value: "CE", text: "CE" },
    { value: "DF", text: "DF" },
    { value: "ES", text: "ES" },
    { value: "GO", text: "GO" },
    { value: "MA", text: "MA" },
    { value: "MG", text: "MG" },
    { value: "MS", text: "MS" },
    { value: "MT", text: "MT" },
    { value: "PA", text: "PA" },
    { value: "PB", text: "PB" },
    { value: "PE", text: "PE" },
    { value: "PI", text: "PI" },
    { value: "PR", text: "PR" },
    { value: "RJ", text: "RJ" },
    { value: "RN", text: "RN" },
    { value: "RO", text: "RO" },
    { value: "RR", text: "RR" },
    { value: "RS", text: "RS" },
    { value: "SC", text: "SC" },
    { value: "SE", text: "SE" },
    { value: "SP", text: "SP" },
    { value: "TO", text: "TO" },
  ],
  TempoMedioEntrega: [
    { value: '5-10 min', text: '5-10 min' },
    { value: '10-20 min', text: '10-20 min' },
    { value: '15-30 min', text: '15-30 min' },
    { value: '30-45 min', text: '30-45 min' },
    { value: '45-60 min', text: '30-45 min' },
    { value: '60-85 min', text: '60-85 min' },
    { value: '90-120 min', text: '90-120 min' },
    { value: '120-240 min', text: '120-240 min' },
  ]
};
